/*
 * Automatically generated C config: don't edit
 */
#define RTCONFIG_OPTIMIZE_SHARED_LIBS 1
#define RTCONFIG_L2TP 1
#define RTCONFIG_PPTP 1
#define RTCONFIG_EAPOL 1
#undef RTCONFIG_PPTPD
#define RTCONFIG_ACCEL_PPTPD 1
#undef RTCONFIG_HTTPS
#undef RTCONFIG_SSH
#undef RTCONFIG_CIFS
#undef RTCONFIG_JFFS2
#undef RTCONFIG_ZEBRA
#define RTCONFIG_DDNS 1
#define RTCONFIG_L7 1
#undef RTCONFIG_LZO
#define RTCONFIG_IPV6 1
#define RTCONFIG_EBTABLES 1
#define RTCONFIG_EMF 1
#undef RTCONFIG_FANCTRL
#undef RTCONFIG_WIRELESSWAN
#undef RTCONFIG_WIRELESSREPEATER
#undef RTCONFIG_OLD_PARENTALCTRL
#define RTCONFIG_PARENTALCTRL 1
#define RTCONFIG_DSL 1
#undef RTCONFIG_DUALWAN
#define RTCONFIG_USB 1
#undef RTCONFIG_MEDIA_SERVER
#define RTCONFIG_FTP 1
#undef RTCONFIG_FTP_SSL
#undef RTCONFIG_WEBDAV
#undef RTCONFIG_CLOUDSYNC
#define RTCONFIG_SAMBASRV 1
#define RTCONFIG_SAMBA3 1
#define RTCONFIG_USB_EXTRAS 1
#define RTCONFIG_NTFS 1
#undef RTCONFIG_NTFS3G
#define RTCONFIG_USB_PRINTER 1
#define RTCONFIG_USB_MODEM 1
#define RTCONFIG_USB_MODEM_PIN 1
#undef RTCONFIG_USB_BECEEM
#undef RTCONFIG_BRCM_USBAP
#undef RTCONFIG_APP_PREINSTALLED
#undef RTCONFIG_APP_NETINSTALLED
#define RTCONFIG_DNSMASQ 1
#define RTCONFIG_RALINK 1
#define RTCONFIG_RALINK_RT3883 1
#undef RTCONFIG_RALINK_RT3052
#define CONFIG_LIBBCM 1
#define CONFIG_LIBUPNP 1
#define RTCONFIG_WPS 1
#undef RTCONFIG_SHP
#undef RTCONFIG_SFP
#undef RTCONFIG_GROCTRL
#define RTCONFIG_LANWAN_LED 1
#undef RTCONFIG_SWMODE_SWITCH
#define RTCONFIG_WIRELESS_SWITCH 1
#define RTCONFIG_AUTODICT 1
#undef RTCONFIG_ISP_METER
